name: /Users/pavel/Documents/jupyter/hydrograce/env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0
  - backcall=0.1.0
  - boost-cpp=1.72.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - cfitsio=3.470
  - curl=7.69.1
  - decorator=4.4.2
  - entrypoints=0.3
  - esmf=8.0.0
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.1
  - freexl=1.0.5
  - g2clib=1.6.0
  - geos=3.8.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.58.3
  - gsl=2.6
  - hdf4=4.2.13
  - hdf5=1.10.5
  - hdfeos2=2.20
  - hdfeos5=5.1.16
  - icu=64.2
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jedi=0.16.0
  - jpeg=9c
  - json-c=0.13.1
  - jupyter_client=6.1.2
  - jupyter_core=4.6.3
  - kealib=1.4.13
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libcxx=10.0.0
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=3.0.4
  - libgfortran=4.0.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.16
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxml2=2.9.10
  - llvm-openmp=8.0.1
  - lz4-c=1.8.3
  - ncl=6.6.2
  - ncurses=6.1
  - netcdf-fortran=4.5.2
  - numpy=1.18.1
  - openjpeg=2.3.1
  - openmp=8.0.1
  - openssl=1.1.1f
  - parso=0.6.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyngl=1.6.1
  - pynio=1.5.5
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pyzmq=18.1.1
  - readline=8.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - tbb=2018.0.5
  - tiledb=1.7.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - tzcode=2019a
  - udunits2=2.2.27.6
  - wcwidth=0.1.9
  - wheel=0.34.2
  - xerces-c=3.2.2
  - xz=5.2.5
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.4.4

